### ISSUE TITLE
Missing addresses from the agvePayments2.json file

### ISSUE THREAD

**Issue by stanchak** [HoneyIsMoney/payments#1]
Last address on agvePayments1.json is 0x7a0ea4409c480ff41bc8211768fb8947c20a91ec
First address on agvePayments2.json is 0x66ca45e79746984385d185dcc000fae482123072

It appears you skipped 2 addresses from the payouts document here:
https://forum.1hive.org/t/agave-retributions-proposal/2822

Screenshot:
![image0](https://user-images.githubusercontent.com/161990/111042486-7dc02200-83f2-11eb-8796-b5c729295a9f.jpeg)

**Comment by HoneyIsMoney** [comment]
thanks
